"""add price_table

Revision ID: 70a5e15f5b84
Revises: 
Create Date: 2026-02-05 15:22:23.857123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70a5e15f5b84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgr_pedidos_besc_t')
    op.add_column('price_table', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('price_table', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('price_table', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('price_table', 'long_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('price_table', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_price_table_id'), table_name='price_table')
    op.drop_index(op.f('idx_price_table_pn'), table_name='price_table')
    op.drop_constraint(op.f('price_table_pn_key'), 'price_table', type_='unique')
    op.create_index(op.f('ix_price_table_id'), 'price_table', ['id'], unique=False)
    op.create_index(op.f('ix_price_table_pn'), 'price_table', ['pn'], unique=True)
    op.create_foreign_key(None, 'shipments', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_index(op.f('ix_price_table_pn'), table_name='price_table')
    op.drop_index(op.f('ix_price_table_id'), table_name='price_table')
    op.create_unique_constraint(op.f('price_table_pn_key'), 'price_table', ['pn'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_price_table_pn'), 'price_table', ['pn'], unique=False)
    op.create_index(op.f('idx_price_table_id'), 'price_table', ['id'], unique=False)
    op.alter_column('price_table', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('price_table', 'long_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('price_table', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('price_table', 'updated_at')
    op.drop_column('price_table', 'created_at')
    op.create_table('sgr_pedidos_besc_t',
    sa.Column('numero_pedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pedido', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uf', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('dataemissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('situacao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_situacao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_fabricante', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('produto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=18, scale=10), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('valortotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('numero_ultima_nf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_emissao_nf', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
